### PR TITLE
Edit for clarity & fix typos

### PR DESCRIPTION
**Pull request by dcato98**

### CODE REVIEW

**Comment by dcato98** [comment]
Please double check my replacing of "comiable" (I checked Google, this is not a word) with "amiable" in docs/get-started/intro.md - I think this is probably the intended word.

Also let me know if you prefer I squish these commits and I'll do so once I finish reading through the docs.

**Comment by dcato98** [comment]
Okay, I'm done editing docs for today and I just went ahead and squashed my commits. I think this is a really cool project and I hope you find this useful!

**Comment by dapplion** [comment]
@dcato98 Thank you so much for contributing! Do as many commits as you need we can squash them latter. @tropicar Could you take a look?

**Review by tropicar — APPROVED** [review]
Thank you so much for your contribution, I think the changes are so well !

**Pull request merged**
